---
- name: Get Nomad binary
  unarchive: 
    src: "{{ nomad_url }}"
    dest: "{{ nomad_dir }}"
    remote_src: true

- name: Create Nomad group
  group:
    name: nomad
    state: present

- name: Create Nomad user
  user:
    name: nomad
    comment: User for Nomad to run under
    groups: nomad

- name: Create work folder
  file:
    path: /var/nomad
    state: directory
    owner: nomad

- name: Create config folder
  file:
    path: /etc/nomad.d
    state: directory