---
- hosts: all
  vars_files:
  - vars/packages.yml
  - vars/secrets.yml
  vars:
  - region: test-region
  - datacenter: test-dc
  - docker_unsafe_registries:
    - registry.example.com
  
  roles:
  - role: docker
  - role: weave.scope
    vars:
    - cluster_with: "{{ groups['all'] }}"

  - role: consul
    vars:
    - servers: "{{ groups['masters'] }}"
    - version: 0.9.3
    
  - role: nomad
    vars:
    - servers: "{{ groups['masters'] }}"
    - version: 0.7.0-beta1