---
- name: Get Consul binary
  unarchive: 
    src: "{{ consul_url }}"
    dest: "{{ consul_dir }}"
    remote_src: true

- name: Create Consul group
  group:
    name: consul
    state: present

- name: Create Consul user
  user:
    name: consul
    comment: User fro Consul to run under
    groups: consul

- name: Create work folder
  file:
    path: /var/consul
    state: directory
    owner: consul